- name: Ansible Copy Example Local to Remote
  hosts: centos2
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src: ~/ansible/repos/index.php
        dest: /var/www/html
        owner: apache
        group: apache        
        mode: 0644
