- hosts: docker
  vars:
    srv:
      - docker
      - docker.socket
  tasks:
   - name: Make sure Docker is running.
     service: 
        name: "{{ srv }}"
        state: started 
           enabled: yes
        
   - name: Install docker-machine
     shell:
        cmd: base=https://github.com/docker/machine/releases/download/v0.16.0 \
             && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine \
             && sudo mv /tmp/docker-machine /usr/local/bin/docker-machine \
             && chmod +x /usr/local/bin/docker-machine
