- hosts: docker
  tasks:
   - name: Make sure Docker is running.
     service: 
        name: docker
        state: started 
        enabled: yes
        
   - name: Install docker-machine
     shell: >
             base=https://github.com/docker/machine/releases/download/v0.16.0
             && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine 
             && sudo mv /tmp/docker-machine /usr/local/bin/docker-machine 
             && chmod +x /usr/local/bin/docker-machine
     args:
       executable: /bin/bash
